version: '3.9'

services:
  
  asistente:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./imagenes:/app/imagenes
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  data: